### ISSUE TITLE
(SHC) Broken Modules

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [JustOptimize/ShowHiddenChannels#199]
> ShowHiddenChannels has detected that some modules are broken, would you like to start anyway? (This might break the plugin or Discord itself)

I have 0.5.1 installed along with ZeresPluginLibrary 2.0.21.  I have not edited or changed anything and just simply reloaded discord and it no longer works.  There was also no update.

0.5.1 was working yesterday and without changing anything, it no longer does.

It could be discord patching things again like they did recently.. https://github.com/JustOptimize/ShowHiddenChannels/issues/188#issuecomment-2180119202

**Comment by KraZ5M** [comment]
I also have the issue, Won't load any of the hidden channels due to some modules being potentially broken. 
![Discord_kw6ZQaGwk4](https://github.com/user-attachments/assets/32bf82b9-e8ae-4f73-b194-78c8697a7195)

**Comment by JustOptimize** [comment]
I know, I'm working on it

**Comment by Hatlix0** [comment]
@JustOptimize you are the best bro

**Comment by skeidGX** [comment]
Same

**Comment by Ketama303** [comment]
Many thanks for the fix in advance! Thanks for doing all this for anyone to use.

**Comment by PUoinhd** [comment]
@Ketama303 Has the file been fixed? where is the updated folder?

**Comment by danachille** [comment]
same, thanks bro

**Comment by Ketama303** [comment]
@PUoinhd No, I was simply thanking **in advance**. He's working on it, so just simply give it some time.

**Comment by KraZ5M** [comment]
Any update if its been fixed yet or not?

**Comment by BatuXL** [comment]
@JustOptimize Has the file fixed yet, if yes we need the file.

**Comment by FIREPAWER07** [comment]
> @JustOptimize Has the file fixed yet, if yes we need the file.

Hey calm down, let him do his work, when he will be done he will send the update. just be patient

**Comment by Ketama303** [comment]
Another voice of reason appears. Hear hear, @FIREPAWER07

**Comment by JustOptimize** [comment]
Okay, I'm back, had a terrible headache, went to sleep and woke up with the plugin working....
Will be pushing a fix in the next minutes, sorry for taking so long to fix

**Comment by danachille** [comment]
> Okay, I'm back, had a terrible headache, went to sleep and woke up with the plugin working....
> Will be pushing a fix in the next minutes, sorry for taking so long to fix

Thanks man !

**Comment by PUoinhd** [comment]
@JustOptimize thanks friends <3

**Comment by Ketama303** [comment]
@JustOptimize That was pretty quick still. It is as if you have a life of your own, with other responsibilities, besides needing to fix a plugin in your free time. I wish you the best best in your future career! Which I have no doubt will be good.
Do you have a donation link anywhere? I'd like to buy your a few beers or cups of espresso (the good kind).

**Comment by JustOptimize** [comment]
> @JustOptimize That was pretty quick still. It is as if you have a life of your own, with other responsibilities, besides needing to fix a plugin in your free time. I wish you the best best in your future career! Which I have no doubt will be good. Do you have a donation link anywhere? I'd like to buy your a few beers or cups of espresso (the good kind).

Aww thanks, and yes, I have a kofi: https://ko-fi.com/oggetto

**Comment by BatuXL** [comment]
@JustOptimize Youre the best bro.

**Comment by BatuXL** [comment]
Again, the same problem.

**Comment by JustOptimize** [comment]
> Again, the same problem. @JustOptimize 

When I get back home I'll have a look

**Comment by JustOptimize** [comment]
@BatuXL let's keep this for v0.5.1, and use #206 for the latest version
