### ISSUE TITLE
Проблема с плагином!

### ISSUE THREAD

**Issue by PinkYoshi2222** [JustOptimize/ShowHiddenChannels#200]
![image](https://github.com/user-attachments/assets/301b326b-4a88-41c1-943e-c7aa7fdc09b9)

**Comment by DarkAssassin48** [comment]
+

**Comment by PUoinhd** [comment]
I did the JustOptimize method and it doesn't work.
![imagem_2024-08-06_053951834](https://github.com/user-attachments/assets/925ceb1e-d86d-4a39-8981-b2720029a2ac)

**Comment by JustOptimize** [comment]
Duplicate of #199
