### ISSUE TITLE
(SHC) Broken Modules - v0.5.2

### ISSUE THREAD

**Issue by TheGreatTaz** [JustOptimize/ShowHiddenChannels#206]
A new update breaks the plugin again

ShowHiddenChannels has detected that some modules are broken, would you like to start anyway? (This might break the plugin or Discord itself)

**Comment by KraZ5M** [comment]
Same here 
![image](https://github.com/user-attachments/assets/5600eaa5-f464-4280-b49d-31a54ceb5ee5)

**Comment by JustOptimize** [comment]
The `rolePill` module is missing, you can press "Start anyway" with no big probems

**Comment by JustOptimize** [comment]
Fixed with latest release, restart discord and it will show the update popup
