### ISSUE TITLE
Doesnt work properly

### ISSUE THREAD

**Issue by MosesNWA** [JustOptimize/ShowHiddenChannels#210]
![image](https://github.com/user-attachments/assets/9fff4889-995c-408a-b0a3-81ec41b9e269)
Good evening. A friend of mine has the issue, that he can only see the categories on a few servers. We tested it on my own server and he sees the channels. hope you can help us :D

**Comment by JustOptimize** [comment]
The categories could be empty, make him disable "show hidden categories" if he doesn't want this feature, can't reproduce
