### ISSUE TITLE
It looks like this was fixed

### ISSUE THREAD

**Issue by XxXBOBBY99ASXxX** [JustOptimize/ShowHiddenChannels#212]
I just tried to plugin and none of the servers I'm in show the names of hidden channels

**Comment by JustOptimize** [comment]
Have you enabled the hide private channels experiment? if not then you could use this https://github.com/JustOptimize/ShowHiddenChannels/blob/fix/channel_names/ShowHiddenChannels.plugin.js

Warning: This is detectable, so if discord wanted to ban shc it could ban the users using it, i'm not responsible etc etc. That said I've been using it for at least 2 weeks and nothing happened 🤷🏻‍♂️

**Comment by JustOptimize** [comment]
@XxXBOBBY99ASXxX news?

**Comment by XxXBOBBY99ASXxX** [comment]
The original plugin works it turns out my better discord install was fucked so I reinstalled and it worked after
