### ISSUE TITLE
Broken modules

### ISSUE THREAD

**Issue by lasarai** [JustOptimize/ShowHiddenChannels#221]
I don't know what to add, I've been seeing this error since 8 p.m

![shc](https://github.com/user-attachments/assets/14480d7f-b6ca-4613-81e2-b31292b92dfa)

**Comment by JustOptimize** [comment]
Discord keeps updating stuff, just press start anyway

**Comment by lasarai** [comment]
I click "start anyway" and it shows me on hidden channels "failed to get date" (:

**Comment by JustOptimize** [comment]
> I click "start anyway" and it shows me on hidden channels "failed to get date" (:

that module is missing, what version of discord are you using? (stable, ptb, canary)

**Comment by lasarai** [comment]
stable

**Comment by JustOptimize** [comment]
> stable

can you share the build number? (it's in the bottom left in the settings)
![image](https://github.com/user-attachments/assets/880a5962-a02d-41be-aeed-b162433e560c)

**Comment by lasarai** [comment]
stable 341775 (b8e14e8)

**Comment by leo-liu-exe** [comment]
same on version stable 341883 (fd167e2)

**Comment by KevDu67** [comment]
Doesn't work for me
![image](https://github.com/user-attachments/assets/a9a4ff98-4630-4230-a52a-fc9055a7f20a)

**Comment by JustOptimize** [comment]
@KevDu67 update to latest version

**Comment by kamil004** [comment]
> @KevDu67 update to latest version

Same error.  (also in permission viewer plugin)
Discord v 0.0.324
Plugin v 0.5.5

<img width="575" alt="image" src="https://github.com/user-attachments/assets/86f4adf8-042a-4653-aba9-55d130cc488a">

**Comment by KraZ5M** [comment]
Just opened discord and got the same error!

**Comment by OGDalee** [comment]
Same on stable 342245 (47f50da)

**Comment by JustOptimize** [comment]
I'm waiting for the update, my canary is older that your stable (tested on multiple computers like...wtf), when i get it I'll fix it, don't worry

**Comment by lasarai** [comment]
> I'm waiting for the update, my canary is older that your stable (tested on multiple computers like...wtf), when i get it I'll fix it, don't worry

I'm glad to hear that!

**Comment by JustOptimize** [comment]
Can we split this issue in 2? #223 fixes the broken modules - Failed to get date.
For the "Cannot convert..." error open a new issue (shouldn't be patched with v0.5.6)
