### ISSUE TITLE
(Bug) TypeError: Cannot convert `undefined` or `null` to object

### ISSUE THREAD

**Issue by JustOptimize** [JustOptimize/ShowHiddenChannels#224]
![image](https://github.com/user-attachments/assets/e0f885c1-6765-448b-8e54-c4104da89fe3)

@KevDu67 @kamil004 @KraZ5M @OGDalee @lasarai

Opened this issue since #221 was about broken modules fixed with v0.5.6

**Comment by JustOptimize** [comment]
Just updated to 342575 (4d5e742) and still can't get this error, are you guys just lying to me and didn't update?
If that's the case this is a duplicate of #218

**Comment by OGDalee** [comment]
My regular client updated just now but BD is not launching with it so I tried PTB.

PTB ptb 342575 (4d5e742) was showing the same issue for me as before, but I reinstalled a fresh version of the plugin from here and it's working now. Thank you 😎

**Comment by lasarai** [comment]
After updating SHC to version 0.5.6 and reopening Discord, everything is working as it should, thank you very much for the quick fix! Broken modules notification no longer pops up
