### ISSUE TITLE
Recently stopped working

### ISSUE THREAD

**Issue by phaiz** [JustOptimize/ShowHiddenChannels#227]
The plugin will not load and no error is provided

https://imgur.com/ZJzCUct

**Comment by phaiz** [comment]
Yeah that fixed it thanks. Interesting that BD didn't notify me about an update, it's typically pretty good at doing so.

**Comment by JustOptimize** [comment]
> Yeah that fixed it thanks. Interesting that BD didn't notify me about an update, it's typically pretty good at doing so.

This plugin is not supported by betterdiscord, that's why the only update notification you get is from the plugin itself, therefore, if it breaks compleatly, it won't notify you
